import { defineSemanticTokens } from '@pandacss/dev'

export const iris = defineSemanticTokens.colors({
  '1': { value: { _light: { value: '#fdfdff' }, _dark: { value: '#13131e' } } },
  '2': { value: { _light: { value: '#f8f8ff' }, _dark: { value: '#171625' } } },
  '3': { value: { _light: { value: '#f0f1fe' }, _dark: { value: '#202248' } } },
  '4': { value: { _light: { value: '#e6e7ff' }, _dark: { value: '#262a65' } } },
  '5': { value: { _light: { value: '#dadcff' }, _dark: { value: '#303374' } } },
  '6': { value: { _light: { value: '#cbcdff' }, _dark: { value: '#3d3e82' } } },
  '7': { value: { _light: { value: '#b8baf8' }, _dark: { value: '#4a4a95' } } },
  '8': { value: { _light: { value: '#9b9ef0' }, _dark: { value: '#5958b1' } } },
  '9': { value: { _light: { value: '#5b5bd6' }, _dark: { value: '#5b5bd6' } } },
  '10': { value: { _light: { value: '#5151cd' }, _dark: { value: '#6e6ade' } } },
  '11': { value: { _light: { value: '#5753c6' }, _dark: { value: '#b1a9ff' } } },
  '12': { value: { _light: { value: '#272962' }, _dark: { value: '#e0dffe' } } },
  a1: { value: { _light: { value: '#0000ff02' }, _dark: { value: '#3636fe0e' } } },
  a2: { value: { _light: { value: '#0000ff07' }, _dark: { value: '#564bf916' } } },
  a3: { value: { _light: { value: '#0011ee0f' }, _dark: { value: '#525bff3b' } } },
  a4: { value: { _light: { value: '#000bff19' }, _dark: { value: '#4d58ff5a' } } },
  a5: { value: { _light: { value: '#000eff25' }, _dark: { value: '#5b62fd6b' } } },
  a6: { value: { _light: { value: '#000aff34' }, _dark: { value: '#6d6ffd7a' } } },
  a7: { value: { _light: { value: '#0008e647' }, _dark: { value: '#7777fe8e' } } },
  a8: { value: { _light: { value: '#0008d964' }, _dark: { value: '#7b7afeac' } } },
  a9: { value: { _light: { value: '#0000c0a4' }, _dark: { value: '#6a6afed4' } } },
  a10: { value: { _light: { value: '#0000b6ae' }, _dark: { value: '#7d79ffdc' } } },
  a11: { value: { _light: { value: '#0600abac' }, _dark: { value: '#b1a9ff' } } },
  a12: { value: { _light: { value: '#000246d8' }, _dark: { value: '#e1e0fffe' } } },
  default: { value: '{ colors.iris.9 }' },
  emphasized: { value: '{ colors.iris.10 }' },
  fg: { value: 'white' },
  text: { value: '{ colors.iris.a11 }' },
})
