import { defineSemanticTokens } from '@pandacss/dev'

export const pink = defineSemanticTokens.colors({
  '1': { value: { _light: { value: '#fffcfe' }, _dark: { value: '#191117' } } },
  '2': { value: { _light: { value: '#fef7fb' }, _dark: { value: '#21121d' } } },
  '3': { value: { _light: { value: '#fee9f5' }, _dark: { value: '#37172f' } } },
  '4': { value: { _light: { value: '#fbdcef' }, _dark: { value: '#4b143d' } } },
  '5': { value: { _light: { value: '#f6cee7' }, _dark: { value: '#591c47' } } },
  '6': { value: { _light: { value: '#efbfdd' }, _dark: { value: '#692955' } } },
  '7': { value: { _light: { value: '#e7acd0' }, _dark: { value: '#833869' } } },
  '8': { value: { _light: { value: '#dd93c2' }, _dark: { value: '#a84885' } } },
  '9': { value: { _light: { value: '#d6409f' }, _dark: { value: '#d6409f' } } },
  '10': { value: { _light: { value: '#cf3897' }, _dark: { value: '#de51a8' } } },
  '11': { value: { _light: { value: '#c2298a' }, _dark: { value: '#ff8dcc' } } },
  '12': { value: { _light: { value: '#651249' }, _dark: { value: '#fdd1ea' } } },
  a1: { value: { _light: { value: '#ff00aa03' }, _dark: { value: '#f412bc09' } } },
  a2: { value: { _light: { value: '#e0008008' }, _dark: { value: '#f420bb12' } } },
  a3: { value: { _light: { value: '#f4008c16' }, _dark: { value: '#fe37cc29' } } },
  a4: { value: { _light: { value: '#e2008b23' }, _dark: { value: '#fc1ec43f' } } },
  a5: { value: { _light: { value: '#d1008331' }, _dark: { value: '#fd35c24e' } } },
  a6: { value: { _light: { value: '#c0007840' }, _dark: { value: '#fd51c75f' } } },
  a7: { value: { _light: { value: '#b6006f53' }, _dark: { value: '#fd62c87b' } } },
  a8: { value: { _light: { value: '#af006f6c' }, _dark: { value: '#ff68c8a2' } } },
  a9: { value: { _light: { value: '#c8007fbf' }, _dark: { value: '#fe49bcd4' } } },
  a10: { value: { _light: { value: '#c2007ac7' }, _dark: { value: '#ff5cc0dc' } } },
  a11: { value: { _light: { value: '#b60074d6' }, _dark: { value: '#ff8dcc' } } },
  a12: { value: { _light: { value: '#59003bed' }, _dark: { value: '#ffd3ecfd' } } },
  default: { value: '{ colors.pink.9 }' },
  emphasized: { value: '{ colors.pink.10 }' },
  fg: { value: 'white' },
  text: { value: '{ colors.pink.a11 }' },
})
