export const neutral = {
  '1': { default: 'neutral.light.1', _dark: 'neutral.dark.1' },
  '2': { default: 'neutral.light.2', _dark: 'neutral.dark.2' },
  '3': { default: 'neutral.light.3', _dark: 'neutral.dark.3' },
  '4': { default: 'neutral.light.4', _dark: 'neutral.dark.4' },
  '5': { default: 'neutral.light.5', _dark: 'neutral.dark.5' },
  '6': { default: 'neutral.light.6', _dark: 'neutral.dark.6' },
  '7': { default: 'neutral.light.7', _dark: 'neutral.dark.7' },
  '8': { default: 'neutral.light.8', _dark: 'neutral.dark.8' },
  '9': { default: 'neutral.light.9', _dark: 'neutral.dark.9' },
  '10': { default: 'neutral.light.10', _dark: 'neutral.dark.10' },
  '11': { default: 'neutral.light.11', _dark: 'neutral.dark.11' },
  '12': { default: 'neutral.light.12', _dark: 'neutral.dark.12' },
  a1: { default: 'neutral.light.a1', _dark: 'neutral.dark.a1' },
  a2: { default: 'neutral.light.a2', _dark: 'neutral.dark.a2' },
  a3: { default: 'neutral.light.a3', _dark: 'neutral.dark.a3' },
  a4: { default: 'neutral.light.a4', _dark: 'neutral.dark.a4' },
  a5: { default: 'neutral.light.a5', _dark: 'neutral.dark.a5' },
  a6: { default: 'neutral.light.a6', _dark: 'neutral.dark.a6' },
  a7: { default: 'neutral.light.a7', _dark: 'neutral.dark.a7' },
  a8: { default: 'neutral.light.a8', _dark: 'neutral.dark.a8' },
  a9: { default: 'neutral.light.a9', _dark: 'neutral.dark.a9' },
  a10: { default: 'neutral.light.a10', _dark: 'neutral.dark.a10' },
  a11: { default: 'neutral.light.a11', _dark: 'neutral.dark.a11' },
  a12: { default: 'neutral.light.a12', _dark: 'neutral.dark.a12' },

  default: { default: 'black', _dark: 'white' },
  emphasized: 'neutral.12',
  fg: { default: 'white', _dark: 'black' },
  text: { default: 'black', _dark: 'white' },
}
