export const orange = {
  1: { value: { _light: '{colors.orange._light.1}', _dark: '{colors.orange.dark.1}' } },
  2: { value: { _light: '{colors.orange._light.2}', _dark: '{colors.orange.dark.2}' } },
  3: { value: { _light: '{colors.orange._light.3}', _dark: '{colors.orange.dark.3}' } },
  4: { value: { _light: '{colors.orange._light.4}', _dark: '{colors.orange.dark.4}' } },
  5: { value: { _light: '{colors.orange._light.5}', _dark: '{colors.orange.dark.5}' } },
  6: { value: { _light: '{colors.orange._light.6}', _dark: '{colors.orange.dark.6}' } },
  7: { value: { _light: '{colors.orange._light.7}', _dark: '{colors.orange.dark.7}' } },
  8: { value: { _light: '{colors.orange._light.8}', _dark: '{colors.orange.dark.8}' } },
  9: { value: { _light: '{colors.orange._light.9}', _dark: '{colors.orange.dark.9}' } },
  10: { value: { _light: '{colors.orange._light.10}', _dark: '{colors.orange.dark.10}' } },
  11: { value: { _light: '{colors.orange._light.11}', _dark: '{colors.orange.dark.11}' } },
  12: { value: { _light: '{colors.orange._light.12}', _dark: '{colors.orange.dark.12}' } },
  a1: { value: { _light: '{colors.orange._light.a1}', _dark: '{colors.orange.dark.a1}' } },
  a2: { value: { _light: '{colors.orange._light.a2}', _dark: '{colors.orange.dark.a2}' } },
  a3: { value: { _light: '{colors.orange._light.a3}', _dark: '{colors.orange.dark.a3}' } },
  a4: { value: { _light: '{colors.orange._light.a4}', _dark: '{colors.orange.dark.a4}' } },
  a5: { value: { _light: '{colors.orange._light.a5}', _dark: '{colors.orange.dark.a5}' } },
  a6: { value: { _light: '{colors.orange._light.a6}', _dark: '{colors.orange.dark.a6}' } },
  a7: { value: { _light: '{colors.orange._light.a7}', _dark: '{colors.orange.dark.a7}' } },
  a8: { value: { _light: '{colors.orange._light.a8}', _dark: '{colors.orange.dark.a8}' } },
  a9: { value: { _light: '{colors.orange._light.a9}', _dark: '{colors.orange.dark.a9}' } },
  a10: { value: { _light: '{colors.orange._light.a10}', _dark: '{colors.orange.dark.a10}' } },
  a11: { value: { _light: '{colors.orange._light.a11}', _dark: '{colors.orange.dark.a11}' } },
  a12: { value: { _light: '{colors.orange._light.a12}', _dark: '{colors.orange.dark.a12}' } },

  default: { value: '{colors.orange.9}' },
  emphasized: { value: '{colors.orange.10}' },
  fg: { value: 'white' },
  text: { value: '{colors.orange.a11}' },
}
