export const jade = {
  '1': { default: 'jade.light.1', _dark: 'jade.dark.1' },
  '2': { default: 'jade.light.2', _dark: 'jade.dark.2' },
  '3': { default: 'jade.light.3', _dark: 'jade.dark.3' },
  '4': { default: 'jade.light.4', _dark: 'jade.dark.4' },
  '5': { default: 'jade.light.5', _dark: 'jade.dark.5' },
  '6': { default: 'jade.light.6', _dark: 'jade.dark.6' },
  '7': { default: 'jade.light.7', _dark: 'jade.dark.7' },
  '8': { default: 'jade.light.8', _dark: 'jade.dark.8' },
  '9': { default: 'jade.light.9', _dark: 'jade.dark.9' },
  '10': { default: 'jade.light.10', _dark: 'jade.dark.10' },
  '11': { default: 'jade.light.11', _dark: 'jade.dark.11' },
  '12': { default: 'jade.light.12', _dark: 'jade.dark.12' },
  a1: { default: 'jade.light.a1', _dark: 'jade.dark.a1' },
  a2: { default: 'jade.light.a2', _dark: 'jade.dark.a2' },
  a3: { default: 'jade.light.a3', _dark: 'jade.dark.a3' },
  a4: { default: 'jade.light.a4', _dark: 'jade.dark.a4' },
  a5: { default: 'jade.light.a5', _dark: 'jade.dark.a5' },
  a6: { default: 'jade.light.a6', _dark: 'jade.dark.a6' },
  a7: { default: 'jade.light.a7', _dark: 'jade.dark.a7' },
  a8: { default: 'jade.light.a8', _dark: 'jade.dark.a8' },
  a9: { default: 'jade.light.a9', _dark: 'jade.dark.a9' },
  a10: { default: 'jade.light.a10', _dark: 'jade.dark.a10' },
  a11: { default: 'jade.light.a11', _dark: 'jade.dark.a11' },
  a12: { default: 'jade.light.a12', _dark: 'jade.dark.a12' },

  default: 'jade.9',
  emphasized: 'jade.10',
  fg: 'white',
  text: 'jade.a11',
}
