import type { Metadata } from 'next'
import { Fira_Code, Plus_Jakarta_Sans } from 'next/font/google'
import { PropsWithChildren } from 'react'
import { cx } from 'styled-system/css'
import './global.css'

const body = Plus_Jakarta_Sans({ subsets: ['latin'], variable: '--font-body' })
const code = Fira_Code({ subsets: ['latin'], variable: '--font-code' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = (props: PropsWithChildren) => {
  const { children } = props
  return (
    <html lang="en">
      <body className={cx(body.variable, code.variable)}>{children}</body>
    </html>
  )
}

export default RootLayout
