import { defineConfig } from '@pandacss/dev'

export default defineConfig({
  preflight: false,
  presets: ['@pandacss/preset-base', '@park-ui/panda-preset'],
  outdir: 'styled-system',
  staticCss: {
    recipes: {
      accordion: ['*'],
      alert: ['*'],
      avatar: ['*'],
      badge: ['*'],
      button: ['*'],
      card: ['*'],
      carousel: ['*'],
      checkbox: ['*'],
      code: ['*'],
      colorPicker: ['*'],
      combobox: ['*'],
      datePicker: ['*'],
      dialog: ['*'],
      drawer: ['*'],
      editable: ['*'],
      hoverCard: ['*'],
      icon: ['*'],
      iconButton: ['*'],
      input: ['*'],
      label: ['*'],
      menu: ['*'],
      pagination: ['*'],
      pinInput: ['*'],
      popover: ['*'],
      numberInput: ['*'],
      radioGroup: ['*'],
      radioButtonGroup: ['*'],
      ratingGroup: ['*'],
      segmentGroup: ['*'],
      select: ['*'],
      slider: ['*'],
      splitter: ['*'],
      switchRecipe: ['*'],
      table: ['*'],
      tabs: ['*'],
      tagsInput: ['*'],
      textarea: ['*'],
      toggleGroup: ['*'],
      tooltip: ['*'],
    },
    css: [
      {
        properties: {
          fontWeight: ['*'],
          textStyle: ['*'],
        },
      },
    ],
  },
})
